### ISSUE TITLE
Supported browsers?

### ISSUE THREAD

**Issue by twm** [radiac/django-yarr#46]
When contributing it would be nice to know what sort of browser support we need to aim for.  For example, the positioning of ``.yarr_control`` currently done with JS could be done in pure CSS with ``position: sticky`` if it's not important to support some older browsers.

Likewise, browser-local prefs that are currently stored in cookies would be better placed in ``localStorage`` provided IE 8 isn't a factor---please tell me IE 8 isn't a factor, please...

**Comment by radiac** [comment]
Good point! Ideally I'd say target latest browsers through progressive enhancement - so although all the functionality would be available in IE8, it would not necessarily look as good or be as easy to use.

That said, I'm fairly relaxed about throwing old browsers under the bus if it'll improve things for the rest of us - since most enhancements can be turned off and/or customised through CSS or ``LAYOUT_FIXED``, if support for a specific feature in a specific old browser really matters to someone, they could implement it themselves.

I've added a note about this to the readme.
